package com.healthcare.entity.enums;

public enum DocumentType {
    LAB_RESULT,
    IMAGING_REPORT,
    PATHOLOGY_REPORT,
    PRESCRIPTION,
    DISCHARGE_SUMMARY,
    CONSULTATION_NOTE,
    SURGICAL_REPORT,
    PROGRESS_NOTE,
    INSURANCE_DOCUMENT,
    CONSENT_FORM,
    REFERRAL_LETTER,
    VACCINATION_RECORD,
    ALLERGY_RECORD,
    LICENSE,
    CLINICAL_CERT,
    ACCREDITATION,
    OTHER
}