package com.healthcare.entity.enums;

public enum TransferReason {
    NO_SPECIALIST_AVAILABLE,
    ICU_CAPACITY_FULL,
    REQUIRED_EQUIPMENT_UNAVAILABLE,
    PATIENT_CONDITION_DETERIORATED,
    HIGHER_LEVEL_CARE_NEEDED,
    SPECIALIST_CONSULTATION_REQUIRED,
    SURGICAL_INTERVENTION_NEEDED,
    DIAGNOSTIC_EQUIPMENT_UNAVAILABLE,
    MEDICAL_EMERGENCY,
    OTHER
}